{
    "homeInfo":{
        "title":"首页",
        "href":"static/layer/pages/welcome.html"
    },
    "logoInfo":{
        "title":"多米互娱",
        "image":"static/layer/images/logo.png",
        "href":""
    },
    "menuInfo":[]
}